import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Layout from '@/components/shared/index'
import './globals.css'
import {useDealerData} from "@/hooks/actions"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  let data = await useDealerData();

  return (
    <html lang="en" >
      <body className={`${inter.className} `}>
        <Layout {...data}>{children}</Layout>
      </body>
    </html>
  );
}
